Repository codeforpdx/PASS, pull requests merged in 2023-12, with the labels that each got.

#551 Issue 509/splitting messages inbox outbox
  src/AppRoutes.jsx
  src/components/Messages/Inbox.jsx
  src/components/Messages/MessageButtonGroup.jsx
  src/components/Messages/MessagePagesList.jsx
  src/components/Messages/MessagesLayout.jsx
  src/components/Messages/Outbox.jsx
  src/components/Messages/index.js
  src/pages/Messages.jsx
  test/components/Messages/Inbox.test.jsx
  test/components/Messages/MessageButtonGroup.test.jsx
  test/components/Messages/Outbox.test.jsx
Labels: enhancement

#555 Patching vulnerabilities
  package-lock.json
Labels: git-related

#548 501/navbar hamburger menu and notification bell improvements
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarDesktop.jsx
Labels: enhancement

#558 Mark message unread
  src/components/Messages/MessagePreview.jsx
  src/hooks/useMessageList.js
Labels: enhancement

#553 #549 No whitespace on form submission
  src/components/Form/FormSection.jsx
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/NewMessageModal.jsx
  test/components/Modals/AddContactModal.test.jsx
  test/components/Modals/NewMessageModal.test.jsx
Labels: bug

#561 [Bug] - Include validation for webIds in Add Contacts Modal
  src/components/Modals/AddContactModal.jsx
  test/components/Modals/AddContactModal.test.jsx
Labels: bug

#545 Enhancement 511: Skip Navigation Button
  package-lock.json
  package.json
  src/components/NavBar/NavBarSkipLink.jsx
  src/components/NavBar/index.js
  src/layouts/Layout.jsx
  src/layouts/Main.jsx
  src/theme.js
  test/components/NavBar/NavBarSkipLink.test.jsx
  test/layouts/Main.test.jsx
Labels: enhancement

#451 #413 Convert the "To" field in New Message Modal to select contacts
  src/components/Modals/NewMessageModal.jsx
  test/components/Modals/NewMessageModal.test.jsx
Labels: enhancement
