Repository codeforpdx/PASS, pull requests merged in 2023-07, with the labels that each got.

#293 Removed unused session parameter from createUser
  src/components/Clients/AddClientModal.jsx
  src/model-helpers/User.js
  test/model-helpers/User.test.js
Labels: bug

#274 Issue 271/pass profile page
  package-lock.json
  package.json
  src/App.jsx
  src/AppRoutes.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarLinks.jsx
  src/components/Profile/ProfileImageField.jsx
  src/components/Profile/ProfileInputField.jsx
  src/components/Profile/index.js
  src/constants/rdf_predicates.js
  src/contexts/SignedInUserContext.jsx
  src/model-helpers/Document.js
  src/model-helpers/DocumentList.js
  src/model-helpers/Profile.js
  src/model-helpers/User.js
  src/model-helpers/UserList.js
  src/model-helpers/index.js
  src/routes/Profile.jsx
  src/routes/index.js
  src/utils/index.js
  src/utils/network/session-helper.js
  test/contexts/SignedInUserContext.test.jsx
  test/model-helpers/Document.test.js
  test/model-helpers/Profile.test.js
Labels: enhancement, discovery

#295 Fixed bug for profile image when profileImage is null
  src/contexts/SignedInUserContext.jsx
Labels: bug

#297 Issue 296/initialize-document-acl
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/contexts/SignedInUserContext.jsx
  src/utils/index.js
  src/utils/network/session-core.js
  src/utils/pod-management/pod-helper.js
  test/utils/pod-helper.test.js
  test/utils/session-core.test.js
Labels: enhancement

#282 embed Button components directly into MenuItem components instead of …
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarLinks.jsx
Labels: refactor/optimization

#287 Issue 223/delete client modal scott
  src/components/Clients/AddClientModal.jsx
  src/components/Clients/ClientList.jsx
  src/components/Clients/ClientListTable.jsx
  src/components/Clients/ClientListTableRow.jsx
  src/components/Clients/DeleteClientModal.jsx
  src/components/Clients/index.js
  src/routes/Clients.jsx
  test/components/Clients/DeleteClientModal.test.jsx
Labels: enhancement

#285 Issue 269/upload doc modal
  docs/ZXing_barcode.md
  src/components/Clients/ClientList.jsx
  src/components/Clients/index.js
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FormSection.jsx
  src/components/Form/index.js
  src/components/LogoutModal/index.js
  src/components/Modals/AddClientModal.jsx
  src/components/Modals/DeleteClientModal.jsx
  src/components/Modals/LogoutModal.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/Modals/index.js
  src/components/NavBar/NavBar.jsx
  src/components/Notification/StatusNotification.jsx
  src/routes/Clients.jsx
  src/routes/Documents.jsx
  test/components/Clients/DeleteClientModal.test.jsx
Labels: enhancement, refactor/optimization

#290 Documentation changes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/RESOURCES.md
  docs/ROADMAP.md
  src/assets/logo.png
Labels: documentation

#284 Issue 226/reply messages
  package-lock.json
  package.json
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessagePreview.jsx
  src/components/Messages/NewMessage.jsx
  src/components/Notification/EmptyListNotification.jsx
  src/components/Notification/LoadingAnimation.jsx
  src/routes/Messages.jsx
  src/typedefs.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
Labels: enhancement

#304 Issue 247/update to dayjs
  src/components/Footer/Footer.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/model-helpers/Document.js
  src/model-helpers/User.js
  src/utils/barcode/barcode-date-parser.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  test/contexts/SignedInUserContext.test.jsx
  test/model-helpers/Document.test.js
Labels: enhancement

#312 Issue 310/patching npm vulnerabilities
  package-lock.json
Labels: bug

#275 Issue 220 sort client list
  src/components/Clients/ClientListTable.jsx
  test/components/Clients/ClientsListTable.test.jsx
Labels: enhancement

#309 Issue 308/update status notification
  src/components/Form/FormSection.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/Notification/StatusNotification.jsx
  src/reducers/statusReducer.js
  src/typedefs.js
Labels: bug

#317 313 updating contributing branching instrutions
  docs/CONTRIBUTING.md
  docs/RESOURCES.md
Labels: documentation

#303 testing the styling of pagination per their documentation
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessageStyles.js
Labels: enhancement

#323 Navbar - Messages route ----> icon button
  package-lock.json
  package.json
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarDesktop.jsx
  src/components/NavBar/NavbarLinks.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/NavbarMobile.jsx
  src/components/NavBar/index.js
  test/components/NavBar/NavBar.test.jsx
  test/components/NavBar/NavbarDesktop.test.jsx
  test/components/NavBar/NavbarLoggedOut.test.jsx
  test/components/NavBar/NavbarMobile.test.jsx
Labels: enhancement

#333 Fix oidcIssuer localStorage
  src/components/NavBar/OidcLoginComponent.jsx
Labels: bug

#321 Issue 320/create client profile
  package-lock.json
  package.json
  src/AppRoutes.jsx
  src/components/Clients/ClientList.jsx
  src/components/Clients/ClientListTable.jsx
  src/components/Clients/ClientListTableRow.jsx
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Documents/index.js
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Messages/NewMessage.jsx
  src/components/Modals/AddClientModal.jsx
  src/components/Modals/DeleteClientModal.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarLinks.jsx
  src/components/Notification/LoadingAnimation.jsx
  src/components/Profile/ProfileComponent.jsx
  src/components/Profile/ProfileEditButtonGroup.jsx
  src/components/Profile/ProfileImageField.jsx
  src/components/Profile/ProfileInputField.jsx
  src/components/Profile/index.js
  src/contexts/DocumentListContext.jsx
  src/contexts/SelectedUserContext.jsx
  src/contexts/SignedInUserContext.jsx
  src/contexts/UserDataContext.jsx
  src/contexts/index.js
  src/model-helpers/Profile.js
  src/pages/Clients.jsx
  src/pages/Documents.jsx
  src/pages/Messages.jsx
  src/pages/Profile.jsx
  src/pages/index.js
  src/typedefs.js
  test/App.test.jsx
  test/components/Clients/ClientsListTable.test.jsx
  test/components/NavBar/OidcLoginComponent.test.jsx
  test/components/Profile/ProfileComponent.test.jsx
  test/components/Profile/ProfileImageField.test.jsx
  test/components/Profile/ProfileInputField.test.jsx
  test/model-helpers/Profile.test.js
  test/utils/session-helper.test.js
Labels: enhancement

#347 Issue-346 / Fix link structure in NavMenu
  src/components/NavBar/NavMenu.jsx
Labels: bug

#341 251/update inactivity message
  src/components/Notification/InactivityMessage.jsx
Labels: enhancement, good first issue

#340 Fixed Login onKeyUp
  src/components/NavBar/OidcLoginComponent.jsx
Labels: enhancement, good first issue
