Repository codeforpdx/PASS, pull requests merged in 2023-06, with the labels that each got.

#193 Issue 188/check permission styling updates
  src/components/Form/CheckAclPermsDocContainerForm.jsx
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/routes/UserSection.jsx
Labels: enhancement

#169 Issue 168/convert users to webids
  src/App.jsx
  src/AppRoutes.jsx
  src/components/Form/ManageUsers.jsx
  src/components/Users/UsersList.jsx
  src/contexts/index.js
  src/contexts/userListContext.js
  src/contexts/userListContext.jsx
  src/model-helpers/User.js
  src/model-helpers/UserList.js
  src/model-helpers/index.js
  src/routes/UserSection.jsx
  src/typedefs.js
  src/utils/index.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  test/components/NavBar/OidcLoginComponent.test.jsx
  test/components/NavBar/__snapshots__/OidcLoginComponent.test.jsx.snap
  test/model-helpers/User.test.js
  test/model-helpers/UserList.test.js
Labels: enhancement, discovery

#204 Refactoring custom hooks
  src/hooks/index.js
  src/hooks/useField.js
  src/hooks/useRedirectUrl.js
  src/hooks/useStatusNotification.js
Labels: refactor/optimization

#202 Replace UPLOAD_TYPES and FETCH_TYPES with INTERACTION_TYPES
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/constants/index.js
  src/constants/interaction_types.js
  src/constants/upload_types.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  test/utils/FormSubmissionHelper.test.js
  test/utils/session-helper.test.js
Labels: enhancement

#206 Issue 194/set doc perms styling updates
  src/components/Form/SetAclPermsDocContainerForm.jsx
Labels: enhancement

#210 Issue 195/set file perms styling updates
  src/components/Form/SetAclPermissionForm.jsx
Labels: enhancement

#209 Issue 196/clients page
  src/App.jsx
  src/AppRoutes.jsx
  src/components/Clients/AddClient.jsx
  src/components/Clients/AddClientModal.jsx
  src/components/Clients/ClientList.jsx
  src/components/Clients/ClientListTable.jsx
  src/components/Clients/ClientListTableRow.jsx
  src/components/Clients/index.js
  src/components/Form/FormSection.jsx
  src/components/Form/index.js
  src/components/LogoutModal/LogoutModal.jsx
  src/components/NavBar/NavbarLinks.jsx
  src/components/Users/UsersList.jsx
  src/routes/Clients.jsx
  src/routes/Home.jsx
  src/routes/UserSection.jsx
  src/theme.js
Labels: enhancement, help wanted

#214 Add signed in user context
  __mocks__/@inrupt/solid-client.js
  package.json
  src/App.jsx
  src/AppRoutes.jsx
  src/components/Messages/NewMessage.jsx
  src/contexts/MessageContext.jsx
  src/contexts/SignedInUserContext.jsx
  src/contexts/UserDataContext.jsx
  src/contexts/UserListContext.jsx
  src/contexts/inboxMessageContext.js
  src/contexts/index.js
  src/contexts/outboxMessageContext.js
  src/index.jsx
  src/layouts/Layout.jsx
  src/model-helpers/User.js
  src/routes/Home.jsx
  src/routes/Inbox.jsx
  src/routes/Outbox.jsx
  test/App.test.jsx
  test/contexts/SignedInUserContext.test.jsx
  test/contexts/__snapshots__/SignedInUserContext.test.jsx.snap
  test/routes/Home.test.jsx
  test/routes/__snapshots__/Home.test.jsx.snap
  test/testHelpers.js
Labels: enhancement

#236 Fixes to Development to Master and refactors to DocumentSelection
  CHANGELOG.md
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Notification/StatusMessage.jsx
  src/theme.js
Labels: refactor/optimization

#238 Fixing Login issue in GitHub Pages
  package-lock.json
Labels: bug

#239 Fixes to GitHub Pages due to package-lock.json
  package-lock.json
Labels: bug

#241 [Feature/Hotfix] Use PASS container and use oidcIssuer for webId generation for usernames
  src/components/Clients/AddClient.jsx
  src/components/Clients/ClientList.jsx
  src/components/Form/CheckAclPermsDocContainerForm.jsx
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Messages/NewMessage.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/constants/index.js
  src/constants/solid_provider.js
  src/model-helpers/User.js
  src/model-helpers/UserList.js
  src/routes/Outbox.jsx
  src/utils/cryptography/credentials-helper.js
  src/utils/index.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  test/components/NavBar/OidcLoginComponent.test.jsx
  test/components/NavBar/__snapshots__/OidcLoginComponent.test.jsx.snap
  test/contexts/SignedInUserContext.test.jsx
  test/model-helpers/User.test.js
  test/model-helpers/UserList.test.js
  test/utils/session-core.test.js
  test/utils/session-helper.test.js
Labels: enhancement, refactor/optimization

#242 [Hotfix] Fixes for Master v0.0.5 from Development v0.0.5.1
  package-lock.json
  package.json
  src/components/Clients/AddClient.jsx
  src/components/Clients/ClientList.jsx
  src/components/Form/CheckAclPermsDocContainerForm.jsx
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Messages/NewMessage.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/constants/index.js
  src/constants/solid_provider.js
  src/model-helpers/User.js
  src/model-helpers/UserList.js
  src/routes/Outbox.jsx
  src/utils/cryptography/credentials-helper.js
  src/utils/index.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  test/components/NavBar/OidcLoginComponent.test.jsx
  test/components/NavBar/__snapshots__/OidcLoginComponent.test.jsx.snap
  test/contexts/SignedInUserContext.test.jsx
  test/model-helpers/User.test.js
  test/model-helpers/UserList.test.js
  test/utils/session-core.test.js
  test/utils/session-helper.test.js
Labels: bug

#245 Refactoring StatusNotification/StatusMessage to truncate long file names
  src/components/Form/FormSection.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Notification/StatusMessage.jsx
  src/components/Notification/StatusNotification.jsx
  src/typedefs.js
  src/utils/frontend/FormSubmissionHelper.js
Labels: enhancement

#243 Update selectedUserContext to hold user object rather than username
  src/components/Clients/ClientListTable.jsx
  src/components/Clients/ClientListTableRow.jsx
  src/components/Form/CheckAclPermsDocContainerForm.jsx
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/contexts/UserDataContext.jsx
  src/contexts/selectUserContext.js
Labels: enhancement

#246 Include ability to unselect users from Clients and Forms without submitting forms
  src/components/Clients/ClientListTableRow.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/routes/Forms.jsx
Labels: enhancement

#253 Issue 215/cross pod styling updates
  package-lock.json
  package.json
  src/components/Clients/AddClient.jsx
  src/components/Form/CheckAclPermsDocContainerForm.jsx
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/contexts/MessageContext.jsx
  src/reducers/statusReducer.js
  src/utils/frontend/FormSubmissionHelper.js
  test/utils/FormSubmissionHelper.test.js
Labels: enhancement

#260 Issue 207/inactivity message styling updates
  src/App.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Messages/NewMessage.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/components/Notification/InactivityMessage.jsx
  src/contexts/MessageContext.jsx
  src/contexts/SignedInUserContext.jsx
  src/contexts/UserListContext.jsx
Labels: enhancement

#249 Issue 135/allow upload, fetch, update, and delete of multiple documents
  __mocks__/@inrupt/solid-client.js
  src/components/Clients/ClientListTable.jsx
  src/components/Clients/ClientListTableRow.jsx
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Form/CheckAclPermsDocContainerForm.jsx
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Form/index.js
  src/components/Table/TableStyles.js
  src/constants/doc_types.js
  src/constants/rdf_predicates.js
  src/contexts/DocumentListContext.jsx
  src/contexts/MessageContext.jsx
  src/contexts/SelectedUserContext.jsx
  src/contexts/SignedInUserContext.jsx
  src/contexts/UserDataContext.jsx
  src/contexts/UserListContext.jsx
  src/contexts/index.js
  src/contexts/selectUserContext.js
  src/model-helpers/Document.js
  src/model-helpers/DocumentList.js
  src/model-helpers/UserList.js
  src/model-helpers/index.js
  src/reducers/statusReducer.js
  src/routes/Forms.jsx
  src/utils/barcode/barcode-date-parser.js
  src/utils/barcode/barcode-scan.js
  src/utils/frontend/FormSubmissionHelper.js
  src/utils/frontend/form-helper.js
  src/utils/index.js
  src/utils/network/session-core.js
  test/contexts/SignedInUserContext.test.jsx
  test/helpers/helperFile.txt
  test/helpers/test-globals.js
  test/helpers/testHelpers.js
  test/model-helpers/Document.test.js
  test/utils/FormSubmissionHelper.test.js
  test/utils/session-core.test.js
  vitest.config.js
Labels: enhancement

#254 Issue 250/pass file viewer
  __mocks__/@inrupt/solid-client.js
  src/AppRoutes.jsx
  src/components/Clients/ClientList.jsx
  src/components/Clients/ClientListTableRow.jsx
  src/components/Clients/index.js
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Form/FormSection.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Notification/StatusMessage.jsx
  src/utils/barcode/barcode-scan.js
  src/utils/cryptography/credentials-helper.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  test/utils/session-core.test.js
  test/utils/session-helper.test.js
Labels: enhancement

#270 Issue 267/loading documents spinner
  src/components/Documents/DocumentTable.jsx
  src/components/Notification/Loading.jsx
  src/routes/Clients.jsx
Labels: enhancement, refactor/optimization

#265 Issue 217/consolidate inbox outbox
  src/AppRoutes.jsx
  src/components/Clients/ClientListTableRow.jsx
  src/components/Footer/Footer.jsx
  src/components/Form/index.js
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessagePreview.jsx
  src/components/Messages/MessageStyles.js
  src/components/Messages/NewMessage.jsx
  src/components/Messages/Pagination.jsx
  src/components/Messages/index.js
  src/components/NavBar/NavbarLinks.jsx
  src/contexts/MessageContext.jsx
  src/layouts/Layout.jsx
  src/routes/Documents.jsx
  src/routes/Inbox.jsx
  src/routes/Messages.jsx
  src/routes/Outbox.jsx
  src/routes/index.js
  src/utils/network/session-core.js
Labels: documentation, enhancement, refactor/optimization

#273 Issue 266/placeholder when no documents
  src/components/Clients/ClientList.jsx
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Notification/EmptyListNotification.jsx
  src/components/Notification/LoadingAnimation.jsx
  src/components/Notification/index.js
  src/routes/Clients.jsx
  src/routes/Documents.jsx
Labels: enhancement

#272 Issue 218/addclient styling update
  src/components/Clients/AddClientModal.jsx
  src/components/Form/FormSection.jsx
Labels: enhancement, refactor/optimization

#276 Fixing redundant code from issue 218
  src/components/Clients/AddClient.jsx
  src/components/Clients/AddClientModal.jsx
  src/components/Clients/index.js
  src/components/Form/UploadDocumentForm.jsx
  src/typedefs.js
Labels: refactor/optimization
