Repository codeforpdx/PASS, pull requests merged in 2023-08, with the labels that each got.

#354 Fixed template in AddClientModal
  src/components/Modals/AddClientModal.jsx
Labels: bug

#349 Issue 307/use webID to set permissions
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/utils/network/session-core.js
  test/utils/session-core.test.js
Labels: refactor/optimization

#369 Issue 368/fix-eslint-prettier-windows
  package.json
Labels: bug

#364 Refactor Footer
  src/components/Footer/Footer.jsx
  src/components/Footer/RenderCallToActionSection.jsx
  src/components/Footer/RenderCompanyInfoSection.jsx
  src/components/Footer/RenderCopyrightAndLinksSection.jsx
  src/typedefs.js
Labels: refactor/optimization

#357 Issue 335/device camera uploads
  src/components/Modals/UploadButtonGroup.jsx
  src/components/Modals/UploadDocumentModal.jsx
Labels: enhancement, discovery

#366 Issue 365/update-sendMessageTTL
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
Labels: bug

#330 Issue 286/new message styling
  src/components/Messages/MessagePreview.jsx
  src/components/Messages/NewMessage.jsx
  src/components/Messages/index.js
  src/components/Modals/AddClientModal.jsx
  src/components/Modals/DeleteClientModal.jsx
  src/components/Modals/LogoutModal.jsx
  src/components/Modals/NewMessageModal.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/Modals/index.js
  src/hooks/useField.js
  src/hooks/useStatusNotification.js
  src/pages/Messages.jsx
  src/typedefs.js
Labels: enhancement, refactor/optimization

#374 Updates ROADMAP.md to conform to other doc styling
  docs/ROADMAP.md
Labels: documentation

#372 readme change to help windows users
  README.md
Labels: documentation

#348 Adding logo to navbar/ favicon
  README.md
  index.html
  src/assets/logo.png
  src/assets/pass-logo.png
  src/components/NavBar/NavbarDesktop.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/NavbarMobile.jsx
Labels: enhancement, good first issue

#380 Minor clean-up to root files
  clearDocs.js
  index.html
Labels: refactor/optimization

#362 Rewrite clients with react query
  .eslintrc.js
  package-lock.json
  package.json
  src/App.jsx
  src/AppRoutes.jsx
  src/components/Clients/ClientList.jsx
  src/components/Clients/index.js
  src/components/Contacts/ContactListTable.jsx
  src/components/Contacts/ContactListTableRow.jsx
  src/components/Contacts/index.js
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/DeleteContactModal.jsx
  src/components/Modals/index.js
  src/components/NavBar/NavbarLinks.jsx
  src/components/Notification/EmptyListNotification.jsx
  src/contexts/DocumentListContext.jsx
  src/contexts/MessageContext.jsx
  src/contexts/SessionContext.jsx
  src/contexts/SignedInUserContext.jsx
  src/contexts/UserDataContext.jsx
  src/contexts/UserListContext.jsx
  src/contexts/index.js
  src/hooks/index.js
  src/hooks/useContactsList.js
  src/hooks/useSession.js
  src/model-helpers/User.js
  src/model-helpers/UserList.js
  src/model-helpers/index.js
  src/pages/Clients.jsx
  src/pages/Contacts.jsx
  src/pages/index.js
  src/typedefs.js
  test/components/Clients/DeleteClientModal.test.jsx
  test/components/Contacts/ContactsListTable.test.jsx
  test/components/Contacts/DeleteContactModal.test.jsx
  test/contexts/SignedInUserContext.test.jsx
  test/hooks/useContactsList.test.jsx
  test/model-helpers/User.test.js
  test/model-helpers/UserList.test.js
  test/pages/Contacts.test.jsx
  vite.config.js
Labels: enhancement, discovery, refactor/optimization

#331 Issue 301 revamp status notifications
  src/App.jsx
  src/components/Form/FormSection.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/DeleteContactModal.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/Notification/BasicNotification.jsx
  src/components/Notification/NotificationContainer.jsx
  src/components/Notification/index.js
  src/contexts/NotificationContext.jsx
  src/hooks/useNotification.js
  src/layouts/Layout.jsx
  src/reducers/notificationReducer.js
  src/theme.js
  test/components/Contacts/DeleteContactModal.test.jsx
  test/components/Notification/BasicNotification.test.jsx
  test/components/Notification/NotificationContainer.test.jsx
Labels: enhancement, discovery

#379 Issue 377/private profile info and Issue 387 fixing profile bug
  src/components/NavBar/NavMenu.jsx
  src/components/Profile/ProfileComponent.jsx
  src/components/Profile/ProfileImageField.jsx
  src/constants/rdf_predicates.js
  src/contexts/DocumentListContext.jsx
  src/contexts/SignedInUserContext.jsx
  src/model-helpers/Document.js
  src/model-helpers/DocumentList.js
  src/model-helpers/Profile.js
  src/pages/Profile.jsx
  src/typedefs.js
  src/utils/cryptography/credentials-helper.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  src/utils/pod-management/pod-helper.js
  test/components/Profile/ProfileComponent.test.jsx
  test/components/Profile/ProfileImageField.test.jsx
  test/model-helpers/Profile.test.js
Labels: enhancement

#384 Issue 382/refactor container creation
  src/contexts/MessageContext.jsx
  src/contexts/SignedInUserContext.jsx
  src/utils/index.js
  src/utils/pod-management/pod-helper.js
  test/utils/pod-helper.test.js
Labels: refactor/optimization

#378 Create User Registration Page
  __mocks__/@inrupt/solid-client.js
  env.template
  src/AppRoutes.jsx
  src/components/Modals/index.js
  src/hooks/useContactsList.js
  src/pages/Profile.jsx
  src/pages/Signup.jsx
  src/pages/index.js
  test/pages/Signup.test.jsx
Labels: enhancement

#394 Bug fix for contacts page
  index.html
  src/pages/Profile.jsx
Labels: bug

#392 Delete old notification system
  src/components/Documents/DocumentTableRow.jsx
  src/components/Form/FormSection.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/DeleteContactModal.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/Notification/StatusNotification.jsx
  src/components/Notification/index.js
  src/hooks/index.js
  src/hooks/useStatusNotification.js
  src/typedefs.js
  src/utils/frontend/notification-helper.js
  src/utils/index.js
Labels: enhancement, refactor/optimization

#390 Issue 216/message preview update
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessagePreview.jsx
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/NewMessageModal.jsx
  src/components/Notification/BasicNotification.jsx
  src/components/Profile/ProfileInputField.jsx
  src/index.jsx
  src/layouts/Layout.jsx
  src/pages/Messages.jsx
  src/pages/Profile.jsx
  src/pages/Signup.jsx
Labels: enhancement, refactor/optimization
