Repository codeforpdx/PASS, pull requests merged in 2023-10, with the labels that each got.

#405 389 Revamped Home Page
  public/assets/app-green.png
  public/assets/key-features-green.png
  public/assets/web-security-green.png
  src/assets/demo_barcode.gif
  src/components/Home/HomeSection.jsx
  src/components/Home/KeyFeatures.jsx
  src/pages/Home.jsx
  test/pages/__snapshots__/Home.test.jsx.snap
Labels: enhancement, refactor/optimization

#433 Issue 376: Updated MUI component to used styled component
  src/components/Contacts/ContactListTable.jsx
  src/components/Contacts/ContactListTableRow.jsx
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Table/TableStyles.js
  src/theme.js
Labels: question

#385 373 husky precommit prettier linter
  .husky/pre-commit
  README.md
  package-lock.json
  package.json
  test/utils/credentials-helper.test.js
Labels: enhancement

#445 Issue-444 / fix alt typo for images
  src/components/Home/HomeSection.jsx
  test/pages/__snapshots__/Home.test.jsx.snap
Labels: bug

#455 Improve accessible name for links on home page
  src/components/Footer/RenderCallToActionSection.jsx
  src/components/Footer/RenderCompanyInfoSection.jsx
  src/components/NavBar/NavbarDesktop.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/NavbarMobile.jsx
  src/pages/Home.jsx
  test/pages/__snapshots__/Home.test.jsx.snap
Labels: enhancement

#448 Improve accessibility of labels
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/ConfirmationButton.jsx
  src/components/Modals/ConfirmationModal.jsx
  src/components/Modals/SetAclPermissionsModal.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/pages/Contacts.jsx
  src/pages/Profile.jsx
  test/components/NavBar/NavBar.test.jsx
  test/components/NavBar/NavbarLoggedOut.test.jsx
  test/components/NavBar/OidcLoginComponent.test.jsx
Labels: enhancement

#458 Improve accessible name for images on home page and prop names for HomeSection
  src/components/Footer/RenderCompanyInfoSection.jsx
  src/components/Home/HomeSection.jsx
  src/components/NavBar/NavbarDesktop.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/NavbarMobile.jsx
  src/pages/Home.jsx
  test/components/NavBar/NavbarDesktop.test.jsx
  test/components/NavBar/NavbarLoggedOut.test.jsx
  test/components/NavBar/NavbarMobile.test.jsx
  test/pages/__snapshots__/Home.test.jsx.snap
Labels: enhancement

#462 Issue 461 fix bug templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: bug

#469 Limit size of file upload for profile photo
  src/components/Profile/ProfileImageField.jsx
Labels: enhancement

#468 Patching package vulnerabilities
  package-lock.json
Labels: package-related

#472 Cleaning up existing JSDoc comments; Excluding props for typedefs
  src/components/Contacts/ContactListTable.jsx
  src/components/Contacts/ContactListTableRow.jsx
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Footer/RenderCallToActionSection.jsx
  src/components/Footer/RenderCompanyInfoSection.jsx
  src/components/Footer/RenderCopyrightAndLinksSection.jsx
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FormSection.jsx
  src/components/Home/HomeSection.jsx
  src/components/Home/KeyFeatures.jsx
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessagePreview.jsx
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/ConfirmationButton.jsx
  src/components/Modals/ConfirmationModal.jsx
  src/components/Modals/NewMessageModal.jsx
  src/components/Modals/SetAclPermissionsModal.jsx
  src/components/Modals/UploadButtonGroup.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarDesktop.jsx
  src/components/NavBar/NavbarLinks.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/NavbarMobile.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/components/Notification/BasicNotification.jsx
  src/components/Notification/EmptyListNotification.jsx
  src/components/Notification/InactivityMessage.jsx
  src/components/Notification/LoadingAnimation.jsx
  src/components/Notification/NotificationContainer.jsx
  src/components/Profile/ProfileComponent.jsx
  src/components/Profile/ProfileEditButtonGroup.jsx
  src/components/Profile/ProfileImageField.jsx
  src/components/Profile/ProfileInputField.jsx
  src/contexts/MessageContext.jsx
  src/model-helpers/DocumentList.js
  src/typedefs.js
  src/utils/network/session-core.js
  test/components/Notification/NotificationContainer.test.jsx
Labels: documentation, discovery

#479 [Bug] - Issue-478/fix-reply-functionality
  src/utils/network/session-core.js
Labels: bug

#457 [Enhancement] - Replace existing Contact List with MUI Data Grid
  package-lock.json
  package.json
  src/components/Contacts/ContactListTable.jsx
  src/components/Contacts/ContactListTableRow.jsx
  src/components/Contacts/ContactProfileIcon.jsx
  src/components/Contacts/index.js
  src/components/Profile/ProfileImageField.jsx
  src/pages/Contacts.jsx
  test/components/Contacts/ContactsListTable.test.jsx
  test/components/Profile/ProfileImageField.test.jsx
  test/pages/Contacts.test.jsx
Labels: enhancement

#481 Patching package vulnerabilities
  package-lock.json
Labels: package-related

#476 [Enhancement] - Issue 475/small screen adjustments
  src/components/Form/FormSection.jsx
  src/components/Home/HomeSection.jsx
  src/components/Home/KeyFeatures.jsx
  src/components/Home/index.js
  src/components/Messages/MessageButtonGroup.jsx
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessagePreview.jsx
  src/components/Messages/MessageStyles.js
  src/components/Messages/index.js
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/ConfirmationButton.jsx
  src/components/Modals/ConfirmationModal.jsx
  src/components/Modals/LogoutButton.jsx
  src/components/Modals/NewMessageModal.jsx
  src/components/Modals/SignInModal.jsx
  src/components/Modals/UploadButtonGroup.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/Modals/index.js
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/components/Profile/ProfileComponent.jsx
  src/components/Profile/ProfileEditButtonGroup.jsx
  src/pages/Home.jsx
  src/pages/Messages.jsx
  src/pages/Profile.jsx
  test/components/Form/FormSection.test.jsx
  test/components/Home/HomeSection.test.jsx
  test/components/Home/KeyFeatures.test.jsx
  test/components/Messages/MessageButtonGroup.test.jsx
  test/components/Messages/MessageFolder.test.jsx
  test/components/Messages/MessagePreview.test.jsx
  test/components/Modals/AddContactModal.test.jsx
  test/components/Modals/ConfirmationModal.test.jsx
  test/components/Modals/NewMessageModal.test.jsx
  test/components/Modals/UploadButtonGroup.test.jsx
  test/components/Modals/UploadDocumentModal.test.jsx
  test/components/NavBar/NavBar.test.jsx
  test/components/NavBar/NavbarLoggedOut.test.jsx
  test/components/NavBar/OidcLoginComponent.test.jsx
  test/components/Profile/ProfileComponent.test.jsx
  test/helpers/createMatchMedia.js
  test/pages/__snapshots__/Home.test.jsx.snap
Labels: enhancement, refactor/optimization
