Repository codeforpdx/PASS, pull requests merged in 2023-05, with the labels that each got.

#106 Add some scripts and environment config to allow developers to easily use a local server.
  .env
  .gitignore
  .nvmrc
  Test PDF.pdf
  docs/README.md
  env_templates/README.md
  env_templates/dev.env
  package-lock.json
  package.json
  src/utils/session-helper.js
  test.txt
Labels: enhancement

#107 Update to Issue 43 - Confirmation Modal for logout
  package-lock.json
  package.json
  src/components/Login/Logout.jsx
  src/components/Login/LogoutModal.jsx
  src/components/Login/index.js
Labels: enhancement

#103 Replacing BrowserRouter with HashRouter
  src/hooks/index.js
  src/index.jsx
Labels: bug, enhancement, discovery

#114 Fixing ESLint Pathing
  package.json
  src/utils/session-helper.js
Labels: bug

#118 Issue 115/create footer component
  src/components/Footer/Footer.jsx
  src/components/Login/Login.jsx
  src/theme.js
Labels: enhancement

#120 Issue 119/logout issue
  src/App.jsx
  src/components/Login/Logout.jsx
  src/components/Login/LogoutModal.jsx
  src/hooks/index.js
Labels: bug

#122 Fixing Prettier pathing
  package.json
Labels: bug, discovery

#125 Adding @returns to updateTTLFile JSDoc
  src/utils/session-helper.js
Labels: documentation

#123 Add checksum to ttl documents + a little refactoring
  .github/workflows/ci.yml
  .gitignore
  docs/README.md
  package-lock.json
  package.json
  src/components/Footer/Footer.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Login/Login.jsx
  src/components/Login/index.js
  src/components/Notification/InactivityMessage.jsx
  src/constants/index.js
  src/constants/rdf_predicates.js
  src/constants/upload_types.js
  src/utils/session-core.js
  src/utils/session-helper.js
  src/utils/session-helper.test.js
Labels: documentation, enhancement, discovery

#116 Issue 110/appheader styling updates
  src/components/AppHeader.jsx
  src/components/Forms.jsx
  src/components/Login/Login.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavMenuMobile.jsx
  src/components/NavBar/index.js
  src/components/Users/UserSection.jsx
  src/index.jsx
  src/layouts/Layouts.jsx
  src/style.css
Labels: enhancement

#128 Issue 112/create pass inbox
  .gitignore
  package.json
  src/App.jsx
  src/components/AppHeader.jsx
  src/components/Forms.jsx
  src/components/Inbox/Inbox.jsx
  src/components/Inbox/NewMessage.jsx
  src/components/Inbox/index.js
  src/components/Login/Login.jsx
  src/components/NavBar/NavBar.jsx
  src/components/Notification/InactivityMessage.jsx
  src/components/Users/UserSection.jsx
  src/constants/rdf_predicates.js
  src/layouts/Layouts.jsx
  src/utils/index.js
  src/utils/session-core.js
  src/utils/session-helper.js
  src/utils/session-helper.test.js
Labels: documentation, enhancement

#141 Issue 138/move logout login into navbar
  src/App.jsx
  src/components/Forms.jsx
  src/components/Inbox/Inbox.jsx
  src/components/Login/Login.jsx
  src/components/Login/Logout.jsx
  src/components/Login/index.js
  src/components/LogoutModal/LogoutModal.jsx
  src/components/LogoutModal/index.js
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavMenuMobile.jsx
  src/components/Users/UserSection.jsx
  src/routes/Home.jsx
Labels: enhancement

#137 Allow users to add cryptographically secure signatures to documents
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/components/Form/UploadDocumentForm.jsx
  src/constants/rdf_predicates.js
  src/reducers/statusReducer.js
  src/utils/credentials-helper.js
  src/utils/credentials-helper.test.js
  src/utils/session-core.js
  src/utils/session-helper.js
  vite.config.js
Labels: enhancement, discovery

#145 Refactor form submission
  .github/workflows/ci.yml
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/utils/FormSubmissionHelper.js
  src/utils/FormSubmissionHelper.test.js
  src/utils/index.js
Labels: enhancement

#156 adds new github action to add PASS project to issue on creation
  .github/workflows/add_project_to_issue.yml
Labels: enhancement

#139 WIP: Development barcode related to Issue #79
  package-lock.json
  package.json
  src/assets/demo_barcode.gif
  src/components/Form/UploadDocumentForm.jsx
  src/constants/rdf_predicates.js
  src/utils/barcode-date-parser.js
  src/utils/barcode-scan.js
  src/utils/form-helper.js
  src/utils/session-helper.js
Labels: enhancement, discovery

#154 Issue 143/routes dropdown menu
  index.html
  src/App.jsx
  src/components/Form/CheckAclPermsDocContainerForm.jsx
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/ManageUsers.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavMenuMobile.jsx
  src/components/NavBar/NavbarLinks.jsx
  src/components/NavBar/index.js
  src/index.jsx
Labels: enhancement

#166 Issue 144/enhance design and ux of inactivity notification
  src/components/NavBar/NavBar.jsx
  src/components/Notification/InactivityMessage.jsx
  src/utils/index.js
  src/utils/logout-helper.js
Labels: enhancement

#172 Issue-170/ Refactor Footer for decent mobile view
  src/components/Footer/Footer.jsx
Labels: enhancement, refactoring

#167 allow user to choose identity provider on signin
  package-lock.json
  package.json
  src/App.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/components/Notification/InactivityMessage.jsx
  src/utils/index.js
  src/utils/logout-helper.js
  test/components/NavBar/OidcLoginComponent.test.jsx
  test/components/NavBar/__snapshots__/OidcLoginComponent.test.jsx.snap
  test/utils/FormSubmissionHelper.test.js
  test/utils/credentials-helper.test.js
  test/utils/session-helper.test.js
Labels: enhancement

#171 Issue 155/organizing utils
  src/components/Form/DocumentSelection.jsx
  src/utils/barcode/barcode-date-parser.js
  src/utils/barcode/barcode-scan.js
  src/utils/cryptography/credentials-helper.js
  src/utils/frontend/FormSubmissionHelper.js
  src/utils/frontend/form-helper.js
  src/utils/frontend/notification-helper.js
  src/utils/index.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  test/utils/FormSubmissionHelper.test.js
  test/utils/credentials-helper.test.js
  test/utils/session-helper.test.js
Labels: refactoring

#180 add margin to top of footer
  src/components/Footer/Footer.jsx
Labels: enhancement

#183 Optimizing functions in session-core and updating JSDoc comments
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/typedefs.js
  src/utils/cryptography/credentials-helper.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  test/utils/session-helper.test.js
Labels: refactor/optimization

#179 Development barcode
  .gitignore
  clearDocs.js
  docs/ZXing_barcode.md
  package-lock.json
  package.json
  src/utils/barcode/barcode-date-parser.js
  src/utils/barcode/barcode-scan.js
  src/utils/network/session-helper.js
Labels: documentation

#148 Issue 140/render ttl messages
  package-lock.json
  package.json
  src/App.jsx
  src/components/Inbox/Inbox.jsx
  src/components/Inbox/MessagePreview.jsx
  src/components/Inbox/NewMessage.jsx
  src/components/Inbox/index.js
  src/components/Users/UserSection.jsx
  src/components/Users/UsersList.jsx
  src/contexts/inboxMessageContext.js
  src/contexts/index.js
  src/contexts/selectUserContext.js
  src/contexts/userListContext.js
  src/typedefs.js
  src/types.d.ts
  src/utils/index.js
  src/utils/network/session-core.js
Labels: documentation, enhancement, discovery

#178 Issue 173/delete document styling updates
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/FormSection.jsx
  src/components/Notification/StatusMessage.jsx
  src/components/Notification/StatusNotification.jsx
  src/components/Users/UserSection.jsx
  src/style.css
  src/theme.js
Labels: enhancement

#184 Optimizing functions in session-helper and updating JSDoc comments
  src/utils/network/session-helper.js
Labels: refactor/optimization

#186 Created function to build outbox when logging in for the first time
  src/App.jsx
  src/utils/index.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
Labels: enhancement

#187 Issue 174/cross pod search styling updates
  docs/ZXing_barcode.md
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/UploadDocumentForm.jsx
Labels: enhancement

#198 Issue 197/refactoring-routes
  src/App.jsx
  src/AppRoutes.jsx
  src/components/Inbox/index.js
  src/components/Users/index.js
  src/routes/Forms.jsx
  src/routes/Home.jsx
  src/routes/Inbox.jsx
  src/routes/UserSection.jsx
Labels: refactor/optimization
