Repository codeforpdx/PASS, pull requests merged in 2023-03, with the labels that each got.

#36 Merge Development into Master to deploy to GH Pages
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: enhancement

#45 Updating JSDoc comments in codebase
  docs/README.md
  package-lock.json
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Form/index.js
  src/components/Login/Login.jsx
  src/components/Login/Logout.jsx
  src/components/Login/index.js
  src/components/Notification/StatusMessage.jsx
  src/components/Notification/StatusNotification.jsx
  src/components/Notification/index.js
  src/hooks/index.js
  src/reducers/statusReducer.js
  src/utils/index.js
  src/utils/notification-helper.js
  src/utils/session-core.js
  src/utils/session-helper.js
Labels: documentation

#52 Fixing id from login to logout in Logout.jsx
  src/components/Login/Logout.jsx
Labels: enhancement

#54 Disable Button when application runs
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/hooks/index.js
  src/reducers/statusReducer.js
  src/utils/notification-helper.js
  src/utils/session-core.js
Labels: enhancement

#58 minor changes to vite.config.js and ci.yml to fix GH-pages integration
  .github/workflows/ci.yml
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/hooks/index.js
  src/reducers/statusReducer.js
  src/utils/notification-helper.js
  src/utils/session-core.js
  vite.config.js
Labels: bug

#56 Merging issue-55/general-code-review to Development; Includes guard rails for setDocAclPermission
  CHANGELOG.md
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/FormSection.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Login/Login.jsx
  src/components/Login/Logout.jsx
  src/components/Notification/StatusMessage.jsx
  src/components/Notification/StatusNotification.jsx
  src/hooks/index.js
  src/reducers/statusReducer.js
  src/utils/form-helper.js
  src/utils/index.js
  src/utils/notification-helper.js
  src/utils/session-core.js
  src/utils/session-helper.js
Labels: documentation, enhancement

#63 62 chromes file explorer crashing application
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/UploadDocumentForm.jsx
Labels: bug

#65 Development to master to fix bug causing chrome crash
  .gitignore
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/UploadDocumentForm.jsx
Labels: bug

#67 Issue 66/refactoring form components
  .eslintrc.js
  .gitignore
  CHANGELOG.md
  jsdoc.config.json
  package-lock.json
  package.json
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/DocumentSelection.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/FormSection.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Form/index.js
  src/components/Login/Login.jsx
  src/components/Login/Logout.jsx
  src/components/Login/index.js
  src/components/Notification/StatusMessage.jsx
  src/components/Notification/StatusNotification.jsx
  src/components/Notification/index.js
  src/hooks/index.js
  src/reducers/statusReducer.js
  src/typedefs.js
  src/utils/form-helper.js
  src/utils/index.js
  src/utils/notification-helper.js
  src/utils/session-core.js
  src/utils/session-helper.js
Labels: documentation, enhancement

#70 Issue 69/pass update files
  .eslintrc.js
  CHANGELOG.md
  Test PDF.pdf
  docs/README.md
  src/components/Form/CrossPodQueryForm.jsx
  src/components/Form/CrossPodWriteForm.jsx
  src/components/Form/DeleteDocumentForm.jsx
  src/components/Form/FetchDocumentForm.jsx
  src/components/Form/FormSection.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/UploadDocumentForm.jsx
  src/components/Notification/StatusMessage.jsx
  src/components/Notification/StatusNotification.jsx
  src/components/Notification/index.js
  src/hooks/index.js
  src/reducers/statusReducer.js
  src/typedefs.js
  src/utils/form-helper.js
  src/utils/index.js
  src/utils/notification-helper.js
  src/utils/session-core.js
  src/utils/session-helper.js
  test.txt
Labels: documentation, enhancement

#71 Issue 69/update ttl file
  src/utils/session-core.js
  src/utils/session-helper.js
Labels: enhancement
