Repository codeforpdx/PASS, pull requests merged in 2023-09, with the labels that each got.

#388 Issue 358 - Putting SetAclPermissions into Modal
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Form/FormSection.jsx
  src/components/Form/SetAclPermissionForm.jsx
  src/components/Form/SetAclPermsDocContainerForm.jsx
  src/components/Form/index.js
  src/components/Modals/SetAclPermissionsModal.jsx
  src/components/Modals/index.js
  src/pages/Profile.jsx
  src/typedefs.js
Labels: enhancement, refactor/optimization

#400 Issue 399/create message read status
  src/components/Messages/MessagePreview.jsx
  src/constants/rdf_predicates.js
  src/contexts/MessageContext.jsx
  src/typedefs.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
Labels: enhancement

#401 Clean-up Profile Components
  src/components/Profile/ProfileComponent.jsx
  src/components/Profile/ProfileEditButtonGroup.jsx
  src/components/Profile/ProfileImageField.jsx
  src/typedefs.js
Labels: refactor/optimization

#402 Issue 386/Profile bug for non-existent webIds
  src/components/Contacts/ContactListTableRow.jsx
Labels: bug

#407 Issue 406/PASS logo production bug
  README.md
  index.html
  public/pass-logo.png
  src/components/NavBar/NavbarDesktop.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/NavbarMobile.jsx
Labels: bug

#411 Update JSdoc README
  docs/README.md
Labels: documentation, good first issue

#424 update to PR template for GitHub
  .github/pull_request_template.md
Labels: bug, documentation

#416 Fix Vite alias pathing for Intellisense
  jsconfig.json
Labels: bug

#417 Removing unused useField custom hook
  src/hooks/index.js
  src/hooks/useField.js
  src/typedefs.js
Labels: refactor/optimization

#419 Fixed typo for JSDoc @name for DocumentListContext
  src/contexts/DocumentListContext.jsx
Labels: refactor/optimization

#418 Removing unused statusMessage component and statusReducer
  src/components/Form/FormSection.jsx
  src/components/Notification/StatusMessage.jsx
  src/components/Notification/index.js
  src/reducers/statusReducer.js
  src/typedefs.js
Labels: refactor/optimization

#426 Add Contact - changing client terminology to contact
  src/components/Modals/AddContactModal.jsx
Labels: refactor/optimization

#404 Issue 393 footer enhancement
  src/components/Footer/RenderCallToActionSection.jsx
  src/components/Footer/RenderCompanyInfoSection.jsx
  src/components/Footer/RenderCopyrightAndLinksSection.jsx
Labels: refactor/optimization

#428 Create confirmation modal
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Modals/ConfirmationButton.jsx
  src/components/Modals/ConfirmationModal.jsx
  src/components/Modals/DeleteContactModal.jsx
  src/components/Modals/LogoutModal.jsx
  src/components/Modals/index.js
  src/components/NavBar/NavBar.jsx
  src/hooks/index.js
  src/pages/Contacts.jsx
  src/pages/Profile.jsx
  src/typedefs.js
  test/components/Contacts/DeleteContactModal.test.jsx
Labels: enhancement, refactor/optimization
