Repository codeforpdx/PASS, pull requests merged in 2023-11, with the labels that each got.

#483 Create RDF Collection Hook
  src/hooks/useCivicProfile.js
  src/hooks/useContactsList.js
  src/hooks/useRdfCollection.js
  src/pages/Contacts.jsx
  src/pages/Signup.jsx
  test/hooks/useCivicProfile.test.jsx
  test/hooks/useContactsList.test.jsx
  test/hooks/useRdfCollection.test.jsx
  test/pages/Signup.test.jsx
Labels: refactor/optimization

#460 Bug 454: when clicking on message in inbox the state of the unread me…
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessagePreview.jsx
  src/contexts/MessageContext.jsx
  src/pages/Messages.jsx
  test/pages/Messages.test.jsx
Labels: bug, enhancement

#470 412 enhancement add a login modal to select pod provider
  __mocks__/src/constants/index.js
  env.template
  package.json
  src/components/NavBar/OidcLoginComponent.jsx
  test/components/NavBar/OidcLoginComponent.test.jsx
Labels: enhancement, discovery

#494 Prepend VITE_ to SUGGESTED_OIDC_OPTIONS environment variable
  env.template
Labels: bug

#485 Issue 414/add message to contacts
  src/components/Contacts/ContactListTable.jsx
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/NewMessageModal.jsx
Labels: enhancement

#486 [Enhancement] - Extends screen adjustments to new Civic Profile page and Navbar changes
  src/components/CivicProfileForms/BasicInfo.jsx
  src/components/CivicProfileForms/FinancialInfo.jsx
  src/components/CivicProfileForms/FormLayout.jsx
  src/components/CivicProfileForms/HousingInfo.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarMobile.jsx
  src/layouts/Layout.jsx
  src/pages/CivicProfile.jsx
  test/components/NavBar/NavMenu.test.jsx
  test/components/NavBar/NavbarMobile.test.jsx
  test/pages/CivicProfile.test.jsx
Labels: enhancement

#496 Use snackbar to display new message notifications
  src/components/Modals/NewMessageModal.jsx
Labels: enhancement

#507 [Enhancement/Refactor] - Issue 506/cleanup utils
  src/model-helpers/Document.js
  src/utils/barcode/barcode-scan.js
  src/utils/network/session-helper.js
Labels: refactor/optimization

#493 WIP Enhancement 491: Added more tests for unread messages
  test/pages/Messages.test.jsx
Labels: enhancement

#497 [New Feature] - Issue 488/breadcrumb navigation
  src/AppRoutes.jsx
  src/components/CivicProfileForms/FormList.js
  src/components/Contacts/ContactProfileIcon.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarLinks.jsx
  src/layouts/Breadcrumbs.jsx
  src/layouts/Layout.jsx
  src/pages/Contacts.jsx
  src/pages/Profile.jsx
  test/layouts/Breadcrumbs.test.jsx
  test/layouts/Layout.test.jsx
Labels: refactor/optimization, new feature

#517 Cleanup Constants Directory
  src/constants/doc_types.js
  src/constants/index.js
  src/constants/interaction_types.js
Labels: refactor/optimization

#528 [Enhancement] - Move localStorage.clear to onLogout prop for LogoutButton
  src/components/Modals/ConfirmationModal.jsx
  src/components/NavBar/NavBar.jsx
  src/components/Notification/InactivityMessage.jsx
Labels: enhancement

#526 Removed code related to DOB and privateProfile.ttl
  src/components/Profile/ProfileComponent.jsx
  src/components/Profile/ProfileImageField.jsx
  src/contexts/SignedInUserContext.jsx
  src/model-helpers/Profile.js
  src/pages/Profile.jsx
  test/model-helpers/Profile.test.js
Labels: enhancement, refactor/optimization

#529 Enhancement 489: Migrate existing document table list to mui data grid
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentTableRow.jsx
  src/components/Documents/index.js
  src/pages/Profile.jsx
  test/components/Documents/DocumentTable.test.jsx
Labels: enhancement

#522 Fixed styling of buttons in InactivityMessage modal
  src/components/Notification/InactivityMessage.jsx
Labels: enhancement

#537 Issue 500/sign in modal
  src/components/Modals/SignInModal.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/OidcLoginComponent.jsx
Labels: enhancement

#538 cancel button to top for share all document
  src/components/Modals/SetAclPermissionsModal.jsx
Labels: enhancement

#535 [No Issue] Remove unused credentialing system
  package-lock.json
  package.json
  src/model-helpers/Document.js
  src/utils/cryptography/credentials-helper.js
  src/utils/index.js
  src/utils/network/session-helper.js
  test/model-helpers/Document.test.js
  test/utils/credentials-helper.test.js
  test/utils/session-helper.test.js
Labels: refactor/optimization

#531 Make `h1` hold full title while maintaining formatting
  package-lock.json
  package.json
  src/pages/Home.jsx
Labels: enhancement

#540 Issue 503/pill buttons
  src/components/Home/HomeSection.jsx
  src/components/Messages/MessageButtonGroup.jsx
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessageStyles.js
  src/components/Messages/PaginationStyles.js
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/ConfirmationButton.jsx
  src/components/Modals/ConfirmationModal.jsx
  src/components/Modals/NewMessageModal.jsx
  src/components/Modals/SetAclPermissionsModal.jsx
  src/components/Modals/UploadButtonGroup.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/components/Notification/InactivityMessage.jsx
  src/theme.js
Labels: enhancement

#516 Issue 456/home page structure enhancements
  package-lock.json
  package.json
  src/components/Home/HomeSection.jsx
  src/components/Home/KeyFeatures.jsx
  src/layouts/Layout.jsx
  src/pages/Home.jsx
  test/components/Home/HomeSection.test.jsx
  test/components/Home/KeyFeatures.test.jsx
  test/pages/Home.test.jsx
  test/pages/__snapshots__/Home.test.jsx.snap
Labels: enhancement, refactor/optimization

#541 Add max height for autocomplete and signInModal components
  src/components/Modals/SignInModal.jsx
  src/components/NavBar/OidcLoginComponent.jsx
Labels: enhancement

#544 Cleaned up v0.10.0 as well as removing unused functions from utils
  src/components/Messages/MessageButtonGroup.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/constants/doc_types.js
  src/model-helpers/Document.js
  src/pages/Messages.jsx
  src/utils/barcode/barcode-scan.js
  src/utils/network/session-helper.js
  test/utils/session-helper.test.js
Labels: refactor/optimization

#514 [Enhancement/Refactor]- Issue 509/create new use message list hook
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/MessagePreview.jsx
  src/components/Modals/NewMessageModal.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarDesktop.jsx
  src/contexts/MessageContext.jsx
  src/contexts/UserDataContext.jsx
  src/contexts/index.js
  src/hooks/index.js
  src/hooks/useMessageList.js
  src/hooks/useRdfCollection.js
  src/pages/Messages.jsx
  src/pages/Profile.jsx
  src/utils/index.js
  src/utils/network/session-core.js
  src/utils/network/session-helper.js
  src/utils/pod-management/pod-helper.js
  test/components/Contacts/ContactsListTable.test.jsx
  test/components/Messages/MessagePreview.test.jsx
  test/components/Modals/NewMessageModal.test.jsx
  test/components/NavBar/NavBar.test.jsx
  test/components/NavBar/NavMenu.test.jsx
  test/components/NavBar/NavbarDesktop.test.jsx
  test/hooks/useMessageList.test.jsx
  test/pages/Contacts.test.jsx
  test/pages/Messages.test.jsx
Labels: enhancement, refactor/optimization

#546 536 enhancement confirmation modal for uploading docs
  src/components/Form/FormSection.jsx
  src/components/Modals/ConfirmationModal.jsx
  src/components/Modals/UploadDocumentConfirmationModal.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/NavBar/NavBar.jsx
  src/pages/Contacts.jsx
  src/pages/Profile.jsx
  test/components/Modals/ConfirmationModal.test.jsx
  test/components/Modals/UploadDocumentModal.test.jsx
Labels: enhancement, refactor/optimization
