Repository codeforpdx/PASS, pull requests merged in 2024-11, with the labels that each got.

#683 [Enhancement] - Issue-682/create documents route
  package-lock.json
  package.json
  src/AppRoutes.jsx
  src/components/Documents/DocumentCard.jsx
  src/components/Documents/DocumentsDesktop.jsx
  src/components/NavBar/NavMenu.jsx
  src/components/NavBar/NavbarLinks.jsx
  src/layouts/Layout.jsx
  src/pages/Documents.jsx
  src/pages/Profile.jsx
  src/pages/index.js
  test/components/Documents/DocumentsDesktop.test.jsx
  test/pages/Profile.test.jsx
Labels: refactor/optimization

#684 [Enhancement] - Issue 682/documents styling fixes
  src/components/Contacts/ContactListTable.jsx
  src/components/Documents/DocumentTable.jsx
  src/components/Footer/Footer.jsx
  src/layouts/Breadcrumbs.jsx
  src/pages/Documents.jsx
  src/pages/Home.jsx
  src/pages/Profile.jsx
Labels: enhancement, refactor/optimization

#692 Issue 690/add copywebid desktop contacts
  src/components/Contacts/ContactListTableDesktop.jsx
  src/components/Contacts/ContactListTableMobile.jsx
  src/pages/Contacts.jsx
Labels: enhancement
