Repository codeforpdx/PASS, pull requests merged in 2024-06, with the labels that each got.

#649 638/error on login
  src/components/Signup/PodRegistrationForm.jsx
  src/components/Signup/podSignupHelpers/handleHTTPErrors.js
  src/components/Signup/podSignupHelpers/registerPod.js
  src/pages/Signup.jsx
  test/pages/Signup.test.jsx
Labels: bug, enhancement

#647 Fix links in pod registration card
  src/components/Signup/ShowNewPod.jsx
Labels: bug

#633 513 enhancement civic profile housing information form
  src/components/CivicProfileForms/HousingInfo.jsx
  test/components/CivicProfileForms/HousingInfo.test.jsx
Labels: enhancement
