Repository codeforpdx/PASS, pull requests merged in 2024-02, with the labels that each got.

#574 Simplify resize tests
  src/components/Footer/Footer.jsx
  src/components/Form/FormSection.jsx
  src/components/Home/HomeSection.jsx
  src/components/Home/KeyFeatures.jsx
  src/layouts/Layout.jsx
  test/components/Footer/Footer.test.jsx
  test/components/Form/FormSection.test.jsx
  test/components/Home/HomeSection.test.jsx
  test/components/Home/KeyFeatures.test.jsx
  test/layouts/Layout.test.jsx
Labels: refactor/optimization

#570 566 bug tests not cleaned up afterwards
  test/components/Home/HomeSection.test.jsx
  test/components/Messages/MessageFolder.test.jsx
  test/components/Messages/MessagePreview.test.jsx
  test/components/Modals/ConfirmationModal.test.jsx
  test/components/NavBar/NavBar.test.jsx
  test/components/Profile/ProfileComponent.test.jsx
  test/helpers/setup-vitest.js
  test/pages/Home.test.jsx
  vitest.config.js
Labels: refactor/optimization

#577 Updating npm packages with npm audit fix
  package-lock.json
Labels: package-related

#580 [ no issue ] UI tweaks to Profile page
  src/components/Modals/AddContactModal.jsx
  src/components/Profile/ProfileComponent.jsx
  src/components/Profile/ProfileImageField.jsx
  src/components/Profile/ProfileInputField.jsx
  src/pages/Profile.jsx
Labels: enhancement

#575 fixed linting errors, resolved issue
  .eslintrc.js
  .github/workflows/ci.yml
  src/components/Contacts/ContactListTable.jsx
  src/components/Modals/AddContactModal.jsx
  src/hooks/useContactsList.js
  src/pages/Contacts.jsx
  test/components/Modals/AddContactModal.test.jsx
  test/hooks/useContactsList.test.jsx
Labels: enhancement
