Repository codeforpdx/PASS, pull requests merged in 2024-03, with the labels that each got.

#588 Update readme
  README.md
  package-lock.json
  package.json
Labels: documentation

#592 Per Issue #590 - updated Docker.react file to pull node:18.
  Dockerfile.react
Labels: version upgrade

#505 351 add relationship info
  src/components/Modals/AddContactModal.jsx
  src/constants/rdf_predicates.js
  src/constants/relationship_status.js
  src/constants/relationships.js
Labels: enhancement, discovery

#601 No Issue - Fix sharing of one document
  src/components/Documents/DocumentTable.jsx
  src/components/Modals/SetAclPermissionsModal.jsx
  src/utils/network/session-core.js
  test/utils/session-core.test.js
Labels: bug, enhancement

#599 Issue 463/add remove image modal
  src/components/Profile/ProfileImageField.jsx
Labels: enhancement

#600 598 simplify add contact to use username
  env.template
  src/components/Modals/AddContactModal.jsx
  test/components/Modals/AddContactModal.test.jsx
  test/helpers/setup-vitest.js
Labels: enhancement
