Repository codeforpdx/PASS, pull requests merged in 2024-07, with the labels that each got.

#656 Issue 651/reroute civic profile
  src/AppRoutes.jsx
  src/components/CivicProfileForms/BasicInfo.jsx
  src/components/CivicProfileForms/FinancialInfo.jsx
  src/components/CivicProfileForms/FormLayout.jsx
  src/components/CivicProfileForms/FormList.js
  src/components/CivicProfileForms/HousingInfo.jsx
  src/components/CivicProfileForms/index.js
  src/components/Form/FormSection.jsx
  src/components/Modals/AddContactModal.jsx
  src/pages/CivicProfile.jsx
  src/pages/Profile.jsx
  test/components/CivicProfileForms/FinancialInfo.test.jsx
  test/pages/CivicProfile.test.jsx
  test/pages/PersonalProfile.test.jsx
Labels: enhancement, MVP

#657 [Bug fix] - Issue-650/bug fix mismatch pass pod creation
  src/components/Signup/PodRegistrationForm.jsx
  src/components/Signup/ShowNewPod.jsx
  test/pages/Signup.test.jsx
Labels: bug

#658 Issue 635/discovery landing page styling adjustments
  public/assets/app-blue.webp
  public/assets/app-green.png
  public/assets/key-features-blue.webp
  public/assets/key-features-green.png
  public/assets/web-security-blue.webp
  public/assets/web-security-green.png
  src/components/Home/KeyFeatures.jsx
  src/pages/Home.jsx
Labels: enhancement

#653 587: Restyle Sign In
  src/components/Signup/ExistingPodForm.jsx
  src/components/Signup/PodRegistrationForm.jsx
  src/layouts/Layout.jsx
  src/pages/Signup.jsx
Labels: enhancement

#655 Issue 648/contacts mobile view
  src/components/Contacts/ContactListTable.jsx
  src/components/Contacts/ContactListTableDesktop.jsx
  src/components/Contacts/ContactListTableMobile.jsx
  src/components/Contacts/ContactProfileIcon.jsx
  src/components/Contacts/index.js
  src/components/Modals/SetAclPermissionsModal.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavMenu.jsx
  src/hooks/index.js
  src/hooks/useTableSort.js
  src/pages/Contacts.jsx
  test/components/Contacts/ContactListTable.test.jsx
  test/components/Contacts/ContactListTableDesktop.test.jsx
  test/components/Contacts/ContactListTableMobile.test.jsx
  test/components/Contacts/ContactsListTable.test.jsx
  test/components/NavBar/NavBar.test.jsx
Labels: enhancement, MVP
