Repository codeforpdx/PASS, pull requests merged in 2024-04, with the labels that each got.

#604 remove broken github action and add projects to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/add_project_to_issue.yml
Labels: bug

#611 Enhancement update document sharing modal to pull from contacts list (#573)
  src/components/Form/FormSection.jsx
  src/components/Modals/SetAclPermissionsModal.jsx
Labels: enhancement

#616 Issue #615 refetch if null
  src/components/CivicProfileForms/HousingInfo.jsx
  src/hooks/useRdfCollection.js
  test/components/CivicProfileForms/HousingInfo.test.jsx
Labels: bug

#533 Issue 442/basic information form
  src/components/CivicProfileForms/BasicInfo.jsx
  src/components/CivicProfileForms/HousingInfo.jsx
  test/components/CivicProfileForms/BasicInfo.test.jsx
Labels: enhancement

#623 605/theme updates
  src/components/Footer/Footer.jsx
  src/components/Footer/RenderCallToActionSection.jsx
  src/components/Footer/RenderCompanyInfoSection.jsx
  src/components/Home/HomeSection.jsx
  src/components/Messages/MessageButtonGroup.jsx
  src/components/Messages/MessageFolder.jsx
  src/components/Messages/PaginationStyles.js
  src/components/Modals/UploadButtonGroup.jsx
  src/components/Modals/UploadDocumentModal.jsx
  src/components/NavBar/NavBarSkipLink.jsx
  src/components/NavBar/NavbarLoggedOut.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/components/Notification/EmptyListNotification.jsx
  src/components/Profile/ProfileEditButtonGroup.jsx
  src/fonts/RedHatDisplay-Italic-VariableFont_wght.ttf
  src/fonts/RedHatText-Italic-VariableFont_wght.ttf
  src/pages/Contacts.jsx
  src/pages/Home.jsx
  src/pages/Profile.jsx
  src/theme.js
  test/components/Modals/UploadButtonGroup.test.jsx
  test/components/Modals/UploadDocumentModal.test.jsx
Labels: enhancement, refactor/optimization
