Repository codeforpdx/PASS, pull requests merged in 2024-05, with the labels that each got.

#624 Issue 582/add copy button function
  src/components/Modals/AddContactModal.jsx
  src/components/Profile/ProfileComponent.jsx
  src/utils/barcode/barcode-date-parser.js
  src/utils/copy/saveToClipboard.js
  src/utils/index.js
Labels: enhancement

#628 622 standardize all input fields
  src/components/Modals/AddContactModal.jsx
  src/components/Modals/NewMessageModal.jsx
  src/components/Modals/SetAclPermissionsModal.jsx
  src/components/Modals/UploadDocumentModal.jsx
Labels: enhancement, good first issue

#630 627/resolve failing basic info tests
  src/components/CivicProfileForms/BasicInfo.jsx
  test/components/CivicProfileForms/BasicInfo.test.jsx
Labels: bug

#641 [Bug Fix] - Issue 640/fix mui autocomplete errors
  src/components/Modals/NewMessageModal.jsx
  src/components/Modals/SetAclPermissionsModal.jsx
  src/components/NavBar/OidcLoginComponent.jsx
  src/contexts/SignedInUserContext.jsx
Labels: bug
