Repository codeforpdx/PASS, pull requests merged in 2024-12, with the labels that each got.

#698 Add notification for inaccessible documents
  src/components/Documents/DocumentTable.jsx
Labels: enhancement

#700 [Bug Fix] - Issue-699/bug fix contacts message
  env.template
  src/components/Modals/NewMessageModal.jsx
  test/components/Messages/MessagePreview.test.jsx
  test/components/Modals/NewMessageModal.test.jsx
Labels: bug

#702 added configs for css v7 deployment used on opencommons
  config/solid-server/readme.md
  config/solid-server/solid-remote-server-compose.yaml
  config/solid-server/solid-remote-server-config.json
Labels: documentation, enhancement

#703 [Version Upgrade] - Update version number from 1.1.1 to 1.2.0
  package-lock.json
  package.json
Labels: version upgrade

#704 [Version Upgrade] - Updating Master version from 1.1.0 to 1.2.0
  config/solid-server/readme.md
  config/solid-server/solid-remote-server-compose.yaml
  config/solid-server/solid-remote-server-config.json
  env.template
  package-lock.json
  package.json
  src/components/Contacts/ContactListTableDesktop.jsx
  src/components/Contacts/ContactListTableMobile.jsx
  src/components/Documents/DocumentTable.jsx
  src/components/Documents/DocumentsDesktop.jsx
  src/components/Messages/MessagePreview.jsx
  src/components/Modals/NewMessageModal.jsx
  src/pages/Contacts.jsx
  test/components/Messages/MessagePreview.test.jsx
  test/components/Modals/NewMessageModal.test.jsx
Labels: version upgrade
